name: 'sertao_olist'
version: '1.0'
config-version: 2
profile: 'sertao_olist'

model-paths: ['models']
macro-paths: ['macros']
test-paths: ['tests']

models:
  sertao_olist:
    +materialized: view
    staging:
      +schema: silver
    intermediate:
      +schema: silver
    marts:
      +schema: gold
      +materialized: table
